SELECT DISTINCT T.ID_PROCESS 
  FROM TASKS T JOIN PROCESSES P ON P.ID_PROCESS = T.ID_PROCESS
               JOIN MDTASK M ON M.ID_PUP_PROCESS = P.ID_PROCESS
               JOIN MDTASK_FAVORITE MF ON MF.MDTASK_ID = M.ID_MDTASK
               LEFT JOIN DEPARTMENTS D ON D.ID_DEPARTMENT = M.INITDEPARTMENT
               {6}
 WHERE MF.USER_ID = {0}