ALTER TABLE FACTPERCENT 
ADD (RISKSTEPUPFACTOR CHAR(12) );

COMMENT ON COLUMN FACTPERCENT.RISKSTEPUPFACTOR IS 'Повыш. коэфф. за риск';
ALTER TABLE FACTPERCENT
ADD CONSTRAINT FACTPERCENT_CRM_RISK_STEP_FK1 FOREIGN KEY
(RISKSTEPUPFACTOR) REFERENCES CRM_RISK_STEPUP_FACTOR (ITEM_ID);

ALTER TABLE FACTPERCENT 
ADD (rating_RISKSTEPUPFACTOR CHAR(12) );

COMMENT ON COLUMN FACTPERCENT.rating_RISKSTEPUPFACTOR IS 'Повыш. коэфф. за риск';
ALTER TABLE FACTPERCENT
ADD CONSTRAINT FACTPERCENT_CRM_RISK_STEP_FK2 FOREIGN KEY
(rating_RISKSTEPUPFACTOR) REFERENCES CRM_RISK_STEPUP_FACTOR (ITEM_ID);

