ALTER TABLE APPFILES ADD (WHO_DEL NUMBER)
/
ALTER TABLE APPFILES ADD (DATE_OF_DEL DATE)
/
ALTER TABLE APPFILES DROP CONSTRAINT APPFILES_FK03
/
ALTER TABLE APPFILES ADD CONSTRAINT APPFILES_FK03 FOREIGN KEY (ID_DOCUMENT_TYPE) 
REFERENCES DOCUMENTS_TYPE(ID_DOCUMENT_TYPE)ON DELETE SET NULL
/
