update stages s set description_stage='Проведение экспертизы юридического подразделения (инвестиционные и финансовые операции)'
where s.description_stage='Проведение экспертизы юридического подразделения' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update stages s set description_stage='Утверждение экспертизы руководителем юридического подразделения (инвестиционные и финансовые операции)'
where s.description_stage='Утверждение экспертизы руководителем юридического подразделения' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update stages s set description_stage='Экспертиза Юридического подразделения (инвестиционные и финансовые операции)'
where s.description_stage='Экспертиза Юридического подразделения' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update stages s set description_stage='Акцепт экспертизы руководителем Юридического подразделения (инвестиционные и финансовые операции)'
where s.description_stage='Акцепт экспертизы руководителем Юридического подразделения' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update roles s set name_role='Руководитель юридического подразделения (инвестиционные и финансовые операции)'
where s.name_role='Руководитель юридического подразделения' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update roles s set name_role='Сотрудник юридического подразделения (инвестиционные и финансовые операции)'
where s.name_role='Сотрудник юридического подразделения' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update variables s set name_var='Требуется экспертиза Юридическим подразделением (инвестиционные и финансовые операции)'
where s.name_var='Требуется экспертиза Юридическим подразделением' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update variables s set name_var='Акцепт экспертизы Юридического подразделения (инвестиционные и финансовые операции)'
where s.name_var='Акцепт экспертизы Юридического подразделения' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update variables s set name_var='Требуется экспертиза Юридическим подразделением (инвестиционные и финансовые операции)_data_start'
where s.name_var='Требуется экспертиза Юридическим подразделением_data_start' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update variables s set name_var='Требуется экспертиза Юридическим подразделением (инвестиционные и финансовые операции)_data_end'
where s.name_var='Требуется экспертиза Юридическим подразделением_data_end' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update variables s set name_var='Требуется экспертиза Юридическим подразделением (инвестиционные и финансовые операции)_user'
where s.name_var='Требуется экспертиза Юридическим подразделением_user' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update variables s set name_var='экспертиза Юридическим подразделением (инвестиционные и финансовые операции)_user_temp'
where s.name_var='экспертиза Юридическим подразделением_user_temp' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update variables s set name_var='Требуется экспертиза Юридическим подразделением (инвестиционные и финансовые операции)_stage'
where s.name_var='Требуется экспертиза Юридическим подразделением_stage' and
s.id_type_process in (select tp.id_type_process from type_process tp where tp.description_process='Крупный бизнес ГО');
update attributes set value_var='100;Экспертиза Юридического подразделения (инвестиционные и финансовые операции);Дополнительная экспертиза Юридического подразделения (инвестиционные и финансовые операции)' where id_var in
(select v.id_var from variables v where v.name_var='Требуется экспертиза Юридическим подразделением (инвестиционные и финансовые операции)');
