COMMENT ON COLUMN STANDARD_PERIOD_GROUP.DECISION_STAGE IS 'deprecated'
/
CREATE TABLE R_DICISIONSTAGE_STANDARDGROUP (ID_STAGE NUMBER , ID_SPG NUMBER)
/
ALTER TABLE R_DICISIONSTAGE_STANDARDGROUP ADD CONSTRAINT R_DICISIONSTAGE_STANDARDG_FK1 FOREIGN KEY(ID_STAGE)
REFERENCES STAGES(  ID_STAGE)ENABLE
/
ALTER TABLE R_DICISIONSTAGE_STANDARDGROUP ADD CONSTRAINT R_DICISIONSTAGE_STANDARDG_FK2 FOREIGN KEY(  ID_SPG)
REFERENCES STANDARD_PERIOD_GROUP(  ID_SPG)ENABLE
/
insert into R_DICISIONSTAGE_STANDARDGROUP(id_spg,id_stage)
select id_spg,decision_stage from standard_period_group where decision_stage is not null
/

/**
 * Удаление битых ссылок на primary key других таблиц
 */
DELETE FROM WARRANTY 
WHERE 
(ID_PERSON IS NULL AND (ORG IS NULL OR ORG='null'))
OR 
(ID_PERSON IS NOT NULL AND ID_PERSON NOT IN (SELECT ID_PERSON FROM CD_PERSON))
OR
(ORG IS NOT NULL AND ORG NOT IN (SELECT ID_ORG FROM CRM_ORGANIZATION));
COMMIT;

DELETE FROM GARANT 
WHERE 
(ID_PERSON IS NULL AND (ORG IS NULL OR ORG='null'))
OR 
(ID_PERSON IS NOT NULL AND ID_PERSON NOT IN (SELECT ID_PERSON FROM CD_PERSON))
OR
(ORG IS NOT NULL AND ORG NOT IN (SELECT ID_ORG FROM CRM_ORGANIZATION));
COMMIT;
  
DELETE FROM DEPOSIT 
WHERE 
(ID_CRMORG IS NULL OR ID_CRMORG='null')
OR
(ID_CRMORG IS NOT NULL AND ID_CRMORG NOT IN (SELECT ID_ORG FROM CRM_ORGANIZATION));  
COMMIT;

/**
 * Создание внешних ключей СПО
 */
BEGIN
 PKG_DDL_UTILS.EXECUTE_STRING('ALTER TABLE WARRANTY ADD CONSTRAINT WARRANTY_PERSON_FK FOREIGN KEY (ID_PERSON) REFERENCES CD_PERSON(ID_PERSON)');
 PKG_DDL_UTILS.EXECUTE_STRING('ALTER TABLE WARRANTY ADD CONSTRAINT WARRANTY_ORG_FK FOREIGN KEY (ORG) REFERENCES CRM_ORGANIZATION(ID_ORG)');
 PKG_DDL_UTILS.EXECUTE_STRING('ALTER TABLE GARANT ADD CONSTRAINT GARANT_PERSON_FK FOREIGN KEY (ID_PERSON) REFERENCES CD_PERSON(ID_PERSON)');
 PKG_DDL_UTILS.EXECUTE_STRING('ALTER TABLE GARANT ADD CONSTRAINT GARANT_ORG_FK FOREIGN KEY (ORG) REFERENCES CRM_ORGANIZATION(ID_ORG)');
 PKG_DDL_UTILS.EXECUTE_STRING('ALTER TABLE DEPOSIT ADD CONSTRAINT DEPOSIT_ORG_FK FOREIGN KEY (ID_CRMORG) REFERENCES CRM_ORGANIZATION(ID_ORG)');
END;
/

