ALTER TABLE PAYMENT_SCHEDULE 
ADD (TRANCE_ID NUMBER );

ALTER TABLE PAYMENT_SCHEDULE
ADD CONSTRAINT PAYMENT_SCHEDULE_TRANCE_FK1 FOREIGN KEY
(
  TRANCE_ID 
)
REFERENCES TRANCE
(
  ID 
)
ON DELETE SET NULL ENABLE;

COMMENT ON COLUMN PAYMENT_SCHEDULE.TRANCE_ID IS 'номер транша';
