BEGIN
DBMS_OUTPUT.ENABLE(NULL);  
PKG_DDL_UTILS.ADD_FOREIGN_KEY_INDEXES('CPS', NULL, 1);
PKG_DDL_UTILS.ADD_FOREIGN_KEY_INDEXES('USER', NULL, 1);
END;
/
BEGIN
DBMS_OUTPUT.ENABLE(NULL);  

DBMS_OUTPUT.PUT_LINE('USER.COUNT_FOR_SECTION_BINDING');
PKG_DDL_UTILS.NOTE_TIME('SELECT COUNT(*) FROM ( SELECT T.ID FROM ( SELECT U.ID_USER ID, U.EMAIL_ EMAIL, U.ID_ LOGIN, U.FULLNAME, U.ID_DEPARTMENT, G2.ID_ROLE R_ID, G2.ID_ R_KEY, G2.NAME_ R_NAME FROM C_ACT_ID_USER U INNER JOIN C_ACT_ID_MEMBERSHIP M2 ON M2.USER_ID_ = U.ID_ INNER JOIN C_ACT_ID_GROUP G2 ON G2.ID_ = M2.GROUP_ID_ INNER JOIN CPS_SECTION_ROLE SR1 ON SR1.ROLE_ID = G2.ID_ROLE INNER JOIN CPS_SECTION_BINDING SB1 ON SB1.SECTION_ID = SR1.SECTION_ID WHERE SB1.SECTION_BINDING_ID = 3065 AND U.ID_ IN ( SELECT Z.USER_ID_ FROM ( SELECT M.USER_ID_ FROM C_ACT_ID_GROUP G INNER JOIN C_ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = G.ID_ START WITH G.ID_ IN ( SELECT G1.ID_ FROM C_ACT_ID_GROUP G1 INNER JOIN C_ACT_ID_MEMBERSHIP M1 ON M1.GROUP_ID_ = G1.ID_ WHERE M1.USER_ID_ = ''msk33364'' AND G1.ID_ROLE IN ( SELECT SR.ROLE_ID FROM CPS_SECTION_ROLE SR INNER JOIN CPS_SECTION_BINDING SB ON SB.SECTION_ID = SR.SECTION_ID WHERE SB.SECTION_BINDING_ID = 3065 AND SR.IS_CONTROL_ROLE = 1 ) ) CONNECT BY PRIOR G.ID_ = G.PARENT_ROLE_KEY ) Z WHERE EXISTS ( ( SELECT G.ID_ROLE FROM C_ACT_ID_GROUP G INNER JOIN C_ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = G.ID_ WHERE M.USER_ID_ = U.ID_ AND G.ID_ROLE IN ( SELECT SR.ROLE_ID FROM CPS_SECTION_ROLE SR INNER JOIN CPS_SECTION_BINDING SB ON SB.SECTION_ID = SR.SECTION_ID WHERE SB.SECTION_BINDING_ID = 3065 ) ) MINUS ( SELECT SM.ROLE_ID FROM CPS_SECTION_MEMBER SM WHERE SM.SECTION_BINDING_ID = 3065 AND SM.USER_ID = U.ID_USER ) ) ) ) T GROUP BY T.ID )', 1);

DBMS_OUTPUT.PUT_LINE('USER.SELECT');
PKG_DDL_UTILS.NOTE_TIME('SELECT U.ID_USER ID, U.EMAIL_ EMAIL, U.ID_ LOGIN, U.FULLNAME, U.ID_DEPARTMENT FROM C_ACT_ID_USER U WHERE U.ID_USER = 9357', 0);

DBMS_OUTPUT.PUT_LINE('User.SELECT_ALL_FOR_SECTION_BINDING');
PKG_DDL_UTILS.NOTE_TIME('SELECT U.ID_USER ID, U.EMAIL_ EMAIL, U.ID_ LOGIN, U.FULLNAME, U.ID_DEPARTMENT, G2.ID_ROLE R_ID, G2.ID_ R_KEY, G2.NAME_ R_NAME FROM C_ACT_ID_USER U INNER JOIN C_ACT_ID_MEMBERSHIP M2 ON M2.USER_ID_ = U.ID_ INNER JOIN C_ACT_ID_GROUP G2 ON G2.ID_ = M2.GROUP_ID_ INNER JOIN CPS_SECTION_ROLE SR1 ON SR1.ROLE_ID = G2.ID_ROLE INNER JOIN CPS_SECTION_BINDING SB1 ON SB1.SECTION_ID = SR1.SECTION_ID WHERE SB1.SECTION_BINDING_ID = 3065 AND U.ID_ IN ( SELECT Z.USER_ID_ FROM ( SELECT M.USER_ID_ FROM C_ACT_ID_GROUP G INNER JOIN C_ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = G.ID_ START WITH G.ID_ IN ( SELECT G1.ID_ FROM C_ACT_ID_GROUP G1 INNER JOIN C_ACT_ID_MEMBERSHIP M1 ON M1.GROUP_ID_ = G1.ID_ WHERE M1.USER_ID_ = ''msk33364'' AND G1.ID_ROLE IN ( SELECT SR.ROLE_ID FROM CPS_SECTION_ROLE SR INNER JOIN CPS_SECTION_BINDING SB ON SB.SECTION_ID = SR.SECTION_ID WHERE SB.SECTION_BINDING_ID = 3065 AND SR.IS_CONTROL_ROLE = 1 ) ) CONNECT BY PRIOR G.ID_ = G.PARENT_ROLE_KEY ) Z WHERE EXISTS ( ( SELECT G.ID_ROLE FROM C_ACT_ID_GROUP G INNER JOIN C_ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = G.ID_ WHERE M.USER_ID_ = U.ID_ AND G.ID_ROLE IN ( SELECT SR.ROLE_ID FROM CPS_SECTION_ROLE SR INNER JOIN CPS_SECTION_BINDING SB ON SB.SECTION_ID = SR.SECTION_ID WHERE SB.SECTION_BINDING_ID = 3065 ) ) MINUS ( SELECT SM.ROLE_ID FROM CPS_SECTION_MEMBER SM WHERE SM.SECTION_BINDING_ID = 3065 AND SM.USER_ID = U.ID_USER ) ) ) ORDER BY NULL , U.FULLNAME', 0);

DBMS_OUTPUT.PUT_LINE('User.SELECT_BY_KEY');
PKG_DDL_UTILS.NOTE_TIME('SELECT U.ID_USER ID, U.EMAIL_ EMAIL, U.ID_ LOGIN, U.FULLNAME, U.ID_DEPARTMENT FROM C_ACT_ID_USER U WHERE LOWER(U.ID_) = LOWER(''MSK33364'')', 0);

DBMS_OUTPUT.PUT_LINE('Department.SELECT_BY_KEY');
PKG_DDL_UTILS.NOTE_TIME('SELECT D.ID_DEPARTMENT ID, D.FULLNAME, D.SHORTNAME FROM DEPARTMENTS D WHERE D.IS_ACTIVE = 1 AND D.ID_DEPARTMENT = 2070201', 0);

DBMS_OUTPUT.PUT_LINE('Department.SELECT_ALL_BY_SECTION_BINDING_ID');
PKG_DDL_UTILS.NOTE_TIME('SELECT D.ID_DEPARTMENT ID, D.FULLNAME, D.SHORTNAME FROM DEPARTMENTS D WHERE D.ID_DEPARTMENT IN ( SELECT Z.ID_DEPARTMENT FROM ( SELECT U.ID_USER ID, U.EMAIL_ EMAIL, U.ID_ LOGIN, U.FULLNAME, U.ID_DEPARTMENT, G2.ID_ROLE R_ID, G2.ID_ R_KEY, G2.NAME_ R_NAME FROM C_ACT_ID_USER U INNER JOIN C_ACT_ID_MEMBERSHIP M2 ON M2.USER_ID_ = U.ID_ INNER JOIN C_ACT_ID_GROUP G2 ON G2.ID_ = M2.GROUP_ID_ INNER JOIN CPS_SECTION_ROLE SR1 ON SR1.ROLE_ID = G2.ID_ROLE INNER JOIN CPS_SECTION_BINDING SB1 ON SB1.SECTION_ID = SR1.SECTION_ID WHERE SB1.SECTION_BINDING_ID = 3273 AND U.ID_ IN ( SELECT Z.USER_ID_ FROM ( SELECT M.USER_ID_ FROM C_ACT_ID_GROUP G INNER JOIN C_ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = G.ID_ START WITH G.ID_ IN ( SELECT G1.ID_ FROM C_ACT_ID_GROUP G1 INNER JOIN C_ACT_ID_MEMBERSHIP M1 ON M1.GROUP_ID_ = G1.ID_ WHERE M1.USER_ID_ = ''msk33364'' AND G1.ID_ROLE IN ( SELECT SR.ROLE_ID FROM CPS_SECTION_ROLE SR INNER JOIN CPS_SECTION_BINDING SB ON SB.SECTION_ID = SR.SECTION_ID WHERE SB.SECTION_BINDING_ID = 3273 AND SR.IS_CONTROL_ROLE = 1 ) ) CONNECT BY PRIOR G.ID_ = G.PARENT_ROLE_KEY ) Z WHERE EXISTS ( ( SELECT G.ID_ROLE FROM C_ACT_ID_GROUP G INNER JOIN C_ACT_ID_MEMBERSHIP M ON M.GROUP_ID_ = G.ID_ WHERE M.USER_ID_ = U.ID_ AND G.ID_ROLE IN ( SELECT SR.ROLE_ID FROM CPS_SECTION_ROLE SR INNER JOIN CPS_SECTION_BINDING SB ON SB.SECTION_ID = SR.SECTION_ID WHERE SB.SECTION_BINDING_ID = 3273 ) ) MINUS ( SELECT SM.ROLE_ID FROM CPS_SECTION_MEMBER SM WHERE SM.SECTION_BINDING_ID = 3273 AND SM.USER_ID = U.ID_USER ) ) ) ) Z ) ORDER BY D.SHORTNAME', 0);
END;
/
BEGIN
DBMS_OUTPUT.ENABLE(NULL);  
PKG_DDL_UTILS.ADD_FOREIGN_KEY_INDEXES(NULL, NULL, 0);
END;
/



