--liquibase formatted sql

--changeset apavlenko:spo-17.16-TASKTYPE logicalFilePath:spo-17.16-TASKTYPE endDelimiter:/ 
UPDATE MDTASK T SET T.TASKTYPE='l' WHERE T.ID_PUP_PROCESS IN
(SELECT A.ID_PROCESS FROM ATTRIBUTES A
INNER JOIN VARIABLES V ON V.ID_VAR=A.ID_VAR AND V.NAME_VAR LIKE 'Тип кредитной заявки'
WHERE A.VALUE_VAR LIKE 'Лимит')
/
UPDATE MDTASK T SET T.TASKTYPE='p' WHERE T.ID_PUP_PROCESS IN
(SELECT A.ID_PROCESS FROM ATTRIBUTES A
INNER JOIN VARIABLES V ON V.ID_VAR=A.ID_VAR AND V.NAME_VAR LIKE 'Тип кредитной заявки'
WHERE A.VALUE_VAR LIKE 'Сделка')
/
