insert into CPS_SECTION_ROLE_SPO_MAPPING 
select CPS_SECTION_ROLE_SPO_MAP_SEQ.nextval,m.section_role_id,'Клиентский менеджер поддерживающего подразделения' from CPS_SECTION_ROLE_SPO_MAPPING m where m.spo_role_name like 'Клиентский менеджер'
and not exists (select 1 from CPS_SECTION_ROLE_SPO_MAPPING where spo_role_name like 'Клиентский менеджер поддерживающего подразделения');
commit;
ALTER TABLE R_MDTASK_OPER_DECISION 
ADD (ACCEPTED VARCHAR2(2048) );
ALTER TABLE R_MDTASK_OPER_DECISION 
ADD (SPECIALS VARCHAR2(2020) );
COMMENT ON COLUMN R_MDTASK_OPER_DECISION.DESCR IS 'deprecated';
COMMENT ON COLUMN R_MDTASK_OPER_DECISION.AUTHORIZED_PERSON IS 'deprecated';
COMMENT ON COLUMN R_MDTASK_OPER_DECISION.ACCEPTED IS 'принимаются';
COMMENT ON COLUMN R_MDTASK_OPER_DECISION.SPECIALS IS 'особенности принятия решения';
CREATE TABLE OPER_DECISION_DESCRIPTION 
(
  ID NUMBER NOT NULL 
, ID_OPER_DECISION NUMBER NOT NULL 
, DESCRIPTION VARCHAR2(2048) 
, CONSTRAINT OPER_DECISION_DESCRIPTION_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
ALTER TABLE OPER_DECISION_DESCRIPTION
ADD CONSTRAINT OPER_DECISION_DESCRIPTION_FK1 FOREIGN KEY
(
  ID_OPER_DECISION 
)
REFERENCES R_MDTASK_OPER_DECISION
(
  ID 
)
ON DELETE CASCADE ENABLE;
CREATE SEQUENCE OPER_DECISION_DESCRIPTION_seq;
