ALTER TABLE PROCENT ADD (PAY_INT VARCHAR2(200) )
/
COMMENT ON COLUMN PROCENT.ID_PROCENT_ORDER IS 'deprecated'
/
COMMENT ON COLUMN PROCENT.PAY_INT IS 'порядок уплаты процентов'
/
ALTER TABLE INTEREST_PAY ADD (PAY_INT VARCHAR2(200) )
/
COMMENT ON COLUMN INTEREST_PAY.ID_PERIOD_ORDER IS 'deprecated'
/
COMMENT ON COLUMN INTEREST_PAY.PAY_INT IS 'порядок уплаты процентов'
/
BEGIN
PKG_DDL_UTILS.ADD_OBJECT('CD_PAY_INT_VERSION', 
'CREATE TABLE CD_PAY_INT_VERSION (
  ID NUMBER(38) NOT NULL,
  DATE_VERSION TIMESTAMP(6) NOT NULL
)');
PKG_DDL_UTILS.ADD_CONSTRAINT('CD_PAY_INT_VERSION_PK', 'ALTER TABLE CD_PAY_INT_VERSION ADD CONSTRAINT CD_PAY_INT_VERSION_PK PRIMARY KEY (ID)');
PKG_DDL_UTILS.RECREATE_SEQUENCE_FOR_TABLE('CD_PAY_INT_VERSION', 'ID', 'CD_PAY_INT_VERSION_SEQ');
END;
/
BEGIN
PKG_DDL_UTILS.ADD_OBJECT('CD_PAY_INT', 
'CREATE TABLE CD_PAY_INT (
  ID NUMBER(38) NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  ID_VER NUMBER(38) NOT NULL
)');
PKG_DDL_UTILS.ADD_CONSTRAINT('CD_PAY_INT_PK', 'ALTER TABLE CD_PAY_INT ADD CONSTRAINT CD_PAY_INT_PK PRIMARY KEY (ID)');
PKG_DDL_UTILS.ADD_CONSTRAINT('CD_PAY_INT_FK01','ALTER TABLE CD_PAY_INT ADD CONSTRAINT CD_PAY_INT_FK01 FOREIGN KEY (ID_VER) REFERENCES CD_PAY_INT_VERSION (ID)');
PKG_DDL_UTILS.RECREATE_SEQUENCE_FOR_TABLE('CD_PAY_INT', 'ID', 'CD_PAY_INT_SEQ');
END;
/
ALTER TABLE CPS_DEAL_CONDITION DROP CONSTRAINT CPS_DEAL_CONDITION_PARENT_FK
/
ALTER TABLE CPS_DEAL_CONDITION ADD CONSTRAINT CPS_DEAL_CONDITION_PARENT_FK FOREIGN KEY
(ID_PARENT_DEAL_CONDITION) REFERENCES CPS_DEAL_CONDITION (ID_DEAL_CONDITION) ON DELETE SET NULL ENABLE
/