ALTER TABLE R_MDTASK_OTHERGOALS ADD ("ID_CRM_TARGET_TYPE" CHAR(12));
ALTER TABLE R_MDTASK_OTHERGOALS ADD CONSTRAINT R_MDTASK_OTHERGOALS_CRM_T_FK1 FOREIGN KEY ("ID_CRM_TARGET_TYPE") REFERENCES CRM_TARGET_TYPE ("ITEMN_ID") ENABLE;
ALTER TABLE FACTPERCENT ADD ("RATE4DESC" VARCHAR2(2000 CHAR));
ALTER TABLE MDTASK  MODIFY (DEFINITION VARCHAR2(4000 BYTE) );